<a href="https://colab.research.google.com/github/Dubenlaylay1/Math-2024-25-Winter/blob/main/1_Basic_Operations_on_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
####1. Basic Operations on Matrices

In [2]:

# prompt: A = [1, 2], [3,4]
# B = [5,6], [7,8]
# [6, 8], [10, 12] = A + B

import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Addition of matrices A and B
result = A + B

result

array([[ 6,  8],
       [10, 12]])

In [3]:
import numpy as np

A = np.array([[4, 2], [12, 4]])
# Note that we are creating a new array with the specified values.
# Multiplying a numpy array by a scalar multiplies each element.
result = A * (1/2)

# Expected result for verification
expected_result = np.array([[2, 1], [6, 2]])

# Check if the calculated result matches the expected result
is_equal = np.array_equal(result, expected_result)

result, is_equal


(array([[2., 1.],
        [6., 2.]]),
 True)

In [4]:
# prompt: A = np.array([[3, 2], [2, 4]])
# B = np.array([[4, 1], [0, 4]])
# result = np.dot(A, B)
# expected_result = np.array([[18, 11], [16, 18]])
# is_correct = np.array_equal(result, expected_result)

import numpy as np

A = np.array([[3, 2], [2, 4]])
B = np.array([[4, 1], [0, 4]])
result = np.dot(A, B)
expected_result = np.array([[18, 11], [16, 18]])
is_correct = np.array_equal(result, expected_result)

print(f"Result of matrix multiplication:\n{result}")
print(f"Is the result correct?: {is_correct}")

Result of matrix multiplication:
[[12 11]
 [ 8 18]]
Is the result correct?: False
