<a href="https://colab.research.google.com/github/Dubenlaylay1/Math-2024-25-Winter/blob/main/math_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
####1. Basic Operations on Matrices

In [ ]:

# prompt: A = [1, 2], [3,4]
# B = [5,6], [7,8]
# [6, 8], [10, 12] = A + B

import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Addition of matrices A and B
result = A + B

result

array([[ 6,  8],
       [10, 12]])

In [ ]:
import numpy as np

A = np.array([[4, 2], [12, 4]])
# Note that we are creating a new array with the specified values.
# Multiplying a numpy array by a scalar multiplies each element.
result = A * (1/2)

# Expected result for verification
expected_result = np.array([[2, 1], [6, 2]])

# Check if the calculated result matches the expected result
is_equal = np.array_equal(result, expected_result)

result, is_equal


(array([[2., 1.],
        [6., 2.]]),
 True)

In [ ]:
# prompt: A = np.array([[3, 2], [2, 4]])
# B = np.array([[4, 1], [0, 4]])
# result = np.dot(A, B)
# expected_result = np.array([[18, 11], [16, 18]])
# is_correct = np.array_equal(result, expected_result)

import numpy as np

A = np.array([[3, 2], [2, 4]])
B = np.array([[4, 1], [0, 4]])
result = np.dot(A, B)
expected_result = np.array([[18, 11], [16, 18]])
is_correct = np.array_equal(result, expected_result)

print(f"Result of matrix multiplication:\n{result}")
print(f"Is the result correct?: {is_correct}")

Result of matrix multiplication:
[[12 11]
 [ 8 18]]
Is the result correct?: False


In [ ]:
####2. Determinants 2x2 and 3x3


In [ ]:
import sympy as sp

# Define the matrix
A = sp.Matrix([[2, 3], [1, 4]])
A # display the matrix

Matrix([
[2, 3],
[1, 4]])

In [ ]:
(2*4 - 3*1) == A.det()

True

In [ ]:
import sympy as sp

# Define the matrix
A = sp.Matrix([[5, 6], [7, 8]])
A # display the matrix

Matrix([
[5, 6],
[7, 8]])

In [ ]:
(5*8 - 6*7) == A.det()

True

In [ ]:
import sympy as sp

# Define the matrix
A = sp.Matrix([[-1, 2], [3, 0]])
A # display the matrix

Matrix([
[-1, 2],
[ 3, 0]])

In [ ]:
(-1*0 - 3*2) == A.det()

True

In [ ]:
####3x3 Matrices
import sympy as sp

# Define the matrix
A = sp.Matrix([[1, 0, 2], [-1, 3, 1], [2, 4, -2]])
A # display the matrix

Matrix([
[ 1, 0,  2],
[-1, 3,  1],
[ 2, 4, -2]])

In [ ]:
# Select the first row [1, 0, 2]
# Define the appropriate minors
M11 = sp.Matrix([[3, 1], [4, -2]])
M12 = sp.Matrix([[-1, 1], [2, -2]])
M13 = sp.Matrix([[-1, 3], [2, 4]])

# Calculate the determinant
d = 1*M11.det() - 0*M12.det() + 2*M13.det()

d == A.det()

True

In [ ]:
import sympy as sp

# Define the matrix
A = sp.Matrix([[3, 1, -1], [0, 2, 4], [5, 3, 2]])
A # display the matrix

Matrix([
[3, 1, -1],
[0, 2,  4],
[5, 3,  2]])

In [ ]:
# Select the first row [1, 0, 2]
# Define the appropriate minors
M11 = sp.Matrix([[2, 4], [3, 2]])
M12 = sp.Matrix([[0, 4], [5, 2]])
M13 = sp.Matrix([[0, 2], [5, 3]])

# Calculate the determinant
d = 3*M11.det() - 1*M12.det() + -1*M13.det()

d == A.det()

True

In [ ]:
import sympy as sp

# Define the matrix
A = sp.Matrix([[2, -3, 1], [1, 4, -2], [1, 5, 3]])
A # display the matrix


Matrix([
[2, -3,  1],
[1,  4, -2],
[1,  5,  3]])

In [ ]:
# Select the first row [2, -3, 1]
# Define the appropriate minors
M11 = sp.Matrix([[4, -2], [5, 3]])
M12 = sp.Matrix([[1, -2], [1, 3]])
M13 = sp.Matrix([[1, 4], [1, 5]])

# Calculate the determinant
d = 2*M11.det() - -3*M12.det() + 1*M13.det()

d == A.det()

True

In [ ]:
####3. Determinants using Laplace's Expansion

In [ ]:
import sympy as sp

# Define the matrix
A = sp.Matrix([[2, 3, 1], [1, 4, 0], [3, 2, 1]])
A # display the matrix

Matrix([
[2, 3, 1],
[1, 4, 0],
[3, 2, 1]])

In [ ]:
# Select the first row [2, 3, 1]
# Define the appropriate minors
M11 = sp.Matrix([[4, 0], [2, 1]])
M12 = sp.Matrix([[1, 0], [2, 1]])
M13 = sp.Matrix([[1, 4], [3, 2]])

# Calculate the determinant
d = 2*M11.det() - 3*M12.det() + 1*M13.det()

d == A.det()

True

In [ ]:
# Define the matrix
C = sp.Matrix([[2, 3, 1, 4,], [1, 0, 0, 6], [3, 2, 1, 5], [2, 1, 4, 0]])
C # display the matrix

Matrix([
[2, 3, 1, 4],
[1, 0, 0, 6],
[3, 2, 1, 5],
[2, 1, 4, 0]])

In [ ]:
# Verify the correctness of the calculations
M11 = sp.Matrix([[0, 0, 6], [2, 1, 5], [1, 4, 0]])
M12 = sp.Matrix([[1, 0, 6], [3, 1, 5], [2, 4, 0]])
M13 = sp.Matrix([[1, 0, 6], [3, 2, 5], [2, 1, 0]])
M14 = sp.Matrix([[1, 0, 0], [3, 2, 1], [2, 1, 4]])

(2*M11.det() - 3*M12.det() + 1*M13.det() - 4*M14.det()) == C.det()

d = 2*M11.det() - 3*M12.det() + 1*M13.det() - 4*M14.det()
d == C.det()

True

In [ ]:


# 5x5 Matrix
D = sp.Matrix([[2, 3, 1, 4, 5], [1, 4, 0, 0, 7], [3, 0, 0, 0, 0], [2, 1, 4, 3, 2], [1, 2, 3, 4, 5]]) # Separate each row with a comma
D

Matrix([
[2, 3, 1, 4, 5],
[1, 4, 0, 0, 7],
[3, 0, 0, 0, 0],
[2, 1, 4, 3, 2],
[1, 2, 3, 4, 5]])

In [ ]:
# Verify the correctness of the calculations
M11 = sp.Matrix([[4, 0, 0, 7], [0, 0, 0, 0,], [1, 4, 3, 2], [2, 3, 4, 5]])
M12 = sp.Matrix([[1, 0, 0, 7], [3,0, 0, 0], [2, 4, 3, 2], [1, 3, 4, 5]])
M13 = sp.Matrix([[1, 4, 0, 7], [3, 0, 0, 0], [2, 1, 3, 2], [1, 2, 4, 5]])
M14 = sp.Matrix([[1, 4, 0, 7], [3, 0, 0, 0], [2, 1, 4, 2], [1, 2, 3, 5]])
M15 = sp.Matrix([[1, 4, 0, 0], [3, 0, 0, 0], [2, 1, 4, 3], [1, 2, 3, 4]])

(2*M11.det() - 3*M12.det() + 1*M13.det() - 4*M14.det() + 5*M15.det()) == D.det()
d = 2*M11.det() - 3*M12.det() + 1*M13.det() - 4*M14.det() + 5*M15.det()
d == D.det()

True

In [ ]:
####4. Determinants from the Gauss Method and Triangular Matrices