In [ ]:

# prompt: A = [1, 2], [3,4]
# B = [5,6], [7,8]
# [6, 8], [10, 12] = A + B

import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Addition of matrices A and B
result = A + B

result

array([[ 6,  8],
       [10, 12]])

**Write the Matrices Side by Side:** First, let's write matrices A and B side by side:

$$
A = \begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
$$

$$
B = \begin{bmatrix}
5 & 6 \\
7 & 8
\end{bmatrix}
$$

**Add Corresponding Elements:** Now, let's add the elements in the same row and column:

$$
C = \begin{bmatrix}
1 + 5 & 2 + 6 \\
3 + 7 & 4 + 8
\end{bmatrix}
$$


**Result:**

The sum of matrices A and B is:

$ C = \begin{bmatrix}
6 & 8 \\
10 & 12
\end{bmatrix} $



In [ ]:
import numpy as np

A = np.array([[4, 2], [12, 4]])
# Note that we are creating a new array with the specified values.
# Multiplying a numpy array by a scalar multiplies each element.
result = A * (1/2)

# Expected result for verification
expected_result = np.array([[2, 1], [6, 2]])

# Check if the calculated result matches the expected result
is_equal = np.array_equal(result, expected_result)

result, is_equal


(array([[2., 1.],
        [6., 2.]]),
 True)

**Given Matrix:**

$$
A = \begin{bmatrix}
4 & 2 \\
12 & 4
\end{bmatrix}
$$

**Multiplication by $\frac{1}{2}$**

Let's multiply each element of the matrix by 1/2:

$\frac{1}{2}$  * $  \begin{bmatrix}
4 & 2 \\
12 & 4
\end{bmatrix}$

**Result:**
$$
B = \begin{bmatrix}
2 & 1 \\
6 & 2
\end{bmatrix}$$



**Explanation:**

**Why Multiply Each Element?**

When we multiply a matrix by a scalar, we effectively scale the matrix by that scalar factor. Therefore, we multiply each element by the same scalar to maintain this proportion.


In [ ]:
import numpy as np

A = np.array([[3, 2], [2, 4]])
B = np.array([[4, 1], [0, 4]])
result = np.dot(A, B)
expected_result = np.array([[12, 11], [8, 18]])
is_correct = np.array_equal(result, expected_result)

print(f"Result of matrix multiplication:\n{result}")
print(f"Is the result correct?: {is_correct}")


Result of matrix multiplication:
[[12 11]
 [ 8 18]]
Is the result correct?: True


**Multiplication:**
$$
A \cdot B = \begin{bmatrix}
3 & 2 \\
2 & 4
\end{bmatrix}
\cdot
\begin{bmatrix}
4 & 1 \\
0 & 4
\end{bmatrix}
=
\begin{bmatrix}
(3 \cdot 4 + 2 \cdot 0) & (3 \cdot 1 + 2 \cdot 4) \\
(2 \cdot 4 + 4 \cdot 0) & (2 \cdot 1 + 4 \cdot 4)
\end{bmatrix}
=
\begin{bmatrix}
12 & 11 \\
8 & 18
\end{bmatrix}
$$

**Resulting Matrix:**

$$ C = \begin{bmatrix}
12 & 11 \\
8 & 18
\end{bmatrix} $$


